services:
  trading-agent:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: trading-agent:prod
    container_name: trading-agent-prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/app/data
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - NODE_ENV=production

    restart: unless-stopped
