import type { AnalysisEnvelope, RunSummary } from "../types";

/**
 * Representative schema-v2 fixtures mirroring the analyzer writer output and
 * the server's legacy adapter (ticket 05 contract). Used to drive UI tests:
 * success, degraded, invalid, no-setup, and legacy states.
 */

export const v2SuccessEnvelope: AnalysisEnvelope = {
  schema_version: "2",
  symbol: "XAUUSD",
  run_id: "2026-07-26T08:30:00",
  started_at: "2026-07-26T08:30:00",
  completed_at: "2026-07-26T08:31:00",
  status: "success",
  errors: [],
  fatal_error: null,
  deterministic_facts: {
    symbol: "XAUUSD",
    timeframes: {},
    setup_status: "READY",
    direction: "LONG",
    trade_direction: "BULLISH",
    setup_grade: "AAA",
    setup_classification_status: "CLASSIFIED",
    setup_lifecycle_status: "TRIGGERED",
    entry_plan: {
      current_price: 2400.0,
      entry_type: "LIMIT",
      entry_price: 2398.5,
      entry_zone_low: 2395.0,
      entry_zone_high: 2402.0,
      trigger_level: null,
      invalidation_level_id: "level-1",
      invalidation_timeframe: "H4",
      invalidation_price: 2378.0,
      target_price: 2440.0,
      estimated_reward_risk: 2.5,
    },
    rr: { calculated_rr: 2.5, minimum_required_rr: 2.0, rr_pass: true },
    confidence_components: { H1: { confidence_score: 72 } },
    policy: {
      execution_status: "ACTIONABLE",
      actionable: true,
      blockers: [],
      reason_codes: [],
    },
    selected_levels: {},
    latest_structural_events: {},
    latest_liquidity_states: {},
    event_history: {},
    liquidity_history: {},
    validation_status: "VALID",
    validation_errors: [],
    operational: true,
    entry_authorized: false,
    bias: "BULLISH",
    confidence: 72,
  },
  decision: { action: "buy_setup" },
  synthesis: {
    status: "SUCCESS",
    explanation: "deterministic context is bullish",
    risks: ["unexpected news spike"],
    confluences: ["H4 breakout retest"],
    error: null,
  },
  ohlc: {
    D1: [{ time: "2026-07-25T17:00", open: 2350, high: 2370, low: 2345, close: 2365.5 }],
    H4: [],
    H1: [],
  },
};

export const v2DegradedEnvelope: AnalysisEnvelope = {
  schema_version: "2",
  symbol: "EURUSD",
  run_id: "2026-07-26T09:00:00",
  started_at: "2026-07-26T09:00:00",
  completed_at: "2026-07-26T09:01:00",
  status: "degraded",
  errors: ["synthesizer provider unreachable"],
  fatal_error: null,
  deterministic_facts: {
    symbol: "EURUSD",
    timeframes: {},
    setup_status: "READY",
    direction: "SHORT",
    trade_direction: "BEARISH",
    setup_grade: "AA",
    setup_classification_status: "CLASSIFIED",
    setup_lifecycle_status: "TRIGGERED",
    entry_plan: {
      current_price: 1.085,
      entry_type: "MARKET",
      entry_price: 1.085,
      entry_zone_low: 1.0848,
      entry_zone_high: 1.0852,
      trigger_level: null,
      invalidation_level_id: null,
      invalidation_timeframe: null,
      invalidation_price: 1.09,
      target_price: 1.07,
      estimated_reward_risk: 3.0,
    },
    rr: { calculated_rr: 3.0, minimum_required_rr: 2.0, rr_pass: true },
    confidence_components: { H1: { confidence_score: 64 } },
    policy: {
      execution_status: "ACTIONABLE",
      actionable: true,
      blockers: [],
      reason_codes: [],
    },
    selected_levels: {},
    latest_structural_events: {},
    latest_liquidity_states: {},
    event_history: {},
    liquidity_history: {},
    validation_status: "VALID",
    validation_errors: [],
    operational: true,
    entry_authorized: false,
    bias: "BEARISH",
    confidence: 64,
  },
  decision: { action: "sell_setup" },
  synthesis: {
    status: "FAILED",
    explanation: null,
    risks: [],
    confluences: [],
    error: "synthesizer provider unreachable",
  },
  ohlc: { D1: [], H4: [], H1: [] },
};

export const v2InvalidEnvelope: AnalysisEnvelope = {
  schema_version: "2",
  symbol: "GBPUSD",
  run_id: "2026-07-26T10:00:00",
  started_at: "2026-07-26T10:00:00",
  completed_at: "2026-07-26T10:01:00",
  status: "partial",
  errors: ["no valid setup"],
  fatal_error: null,
  deterministic_facts: {
    symbol: "GBPUSD",
    timeframes: {},
    setup_status: "INVALID",
    direction: "NONE",
    trade_direction: "NEUTRAL",
    setup_grade: null,
    setup_classification_status: "NO_SETUP",
    setup_lifecycle_status: "PENDING",
    entry_plan: {
      current_price: null,
      entry_type: null,
      entry_price: null,
      entry_zone_low: null,
      entry_zone_high: null,
      trigger_level: null,
      invalidation_level_id: null,
      invalidation_timeframe: null,
      invalidation_price: null,
      target_price: null,
      estimated_reward_risk: null,
    },
    rr: { calculated_rr: null, minimum_required_rr: 2.0, rr_pass: false },
    confidence_components: {},
    policy: {
      execution_status: "NON_EXECUTABLE",
      actionable: false,
      blockers: [{ type: "no_setup", code: "NO_SETUP", reason: "no valid setup", severity: "blocking" }],
      reason_codes: ["NO_SETUP"],
    },
    selected_levels: {},
    latest_structural_events: {},
    latest_liquidity_states: {},
    event_history: {},
    liquidity_history: {},
    validation_status: "INVALID",
    validation_errors: ["no valid setup"],
    operational: false,
    entry_authorized: false,
    bias: "NEUTRAL",
    confidence: null,
  },
  decision: { action: "no_trade" },
  synthesis: {
    status: "SKIPPED",
    explanation: null,
    risks: [],
    confluences: [],
    error: null,
  },
  ohlc: { D1: [], H4: [], H1: [] },
};

export const v2NoSetupEnvelope: AnalysisEnvelope = {
  schema_version: "2",
  symbol: "NZDUSD",
  run_id: "2026-07-26T11:00:00",
  started_at: "2026-07-26T11:00:00",
  completed_at: "2026-07-26T11:01:00",
  status: "partial",
  errors: [],
  fatal_error: null,
  deterministic_facts: {
    symbol: "NZDUSD",
    timeframes: {},
    setup_status: "NO_SETUP",
    direction: "NONE",
    trade_direction: "NEUTRAL",
    setup_grade: null,
    setup_classification_status: "NO_SETUP",
    setup_lifecycle_status: "PENDING",
    entry_plan: {
      current_price: null,
      entry_type: null,
      entry_price: null,
      entry_zone_low: null,
      entry_zone_high: null,
      trigger_level: null,
      invalidation_level_id: null,
      invalidation_timeframe: null,
      invalidation_price: null,
      target_price: null,
      estimated_reward_risk: null,
    },
    rr: { calculated_rr: null, minimum_required_rr: 2.0, rr_pass: false },
    confidence_components: {},
    policy: {
      execution_status: "NON_EXECUTABLE",
      actionable: false,
      blockers: [],
      reason_codes: ["NO_SETUP"],
    },
    selected_levels: {},
    latest_structural_events: {},
    latest_liquidity_states: {},
    event_history: {},
    liquidity_history: {},
    validation_status: "VALID",
    validation_errors: [],
    operational: false,
    entry_authorized: false,
    bias: "NEUTRAL",
    confidence: 0,
  },
  decision: { action: "no_trade" },
  synthesis: {
    status: "SKIPPED",
    explanation: null,
    risks: [],
    confluences: [],
    error: null,
  },
  ohlc: { D1: [], H4: [], H1: [] },
};

export const legacyEnvelope: AnalysisEnvelope = {
  schema_version: "legacy",
  symbol: "XAUUSD",
  run_id: "2026-07-25T08:30:00",
  started_at: "2026-07-25T08:30:00",
  completed_at: "2026-07-25T08:31:00",
  status: "success",
  errors: [],
  fatal_error: null,
  deterministic_facts: {
    symbol: "XAUUSD",
    timeframes: {},
    setup_status: "UNKNOWN",
    direction: "NONE",
    trade_direction: "NEUTRAL",
    setup_grade: null,
    setup_classification_status: "NO_SETUP",
    setup_lifecycle_status: "UNKNOWN",
    entry_plan: {},
    rr: { calculated_rr: null, minimum_required_rr: 2.0, rr_pass: false },
    confidence_components: {},
    policy: {
      execution_status: "NON_EXECUTABLE",
      actionable: false,
      blockers: [],
      reason_codes: [],
    },
    selected_levels: {},
    latest_structural_events: {},
    latest_liquidity_states: {},
    event_history: {},
    liquidity_history: {},
    validation_status: "UNKNOWN",
    validation_errors: [],
    operational: false,
    entry_authorized: false,
    bias: "bullish",
    confidence: 0.85,
  },
  decision: { action: "no_trade" },
  synthesis: {
    status: "SKIPPED",
    explanation: null,
    risks: [],
    confluences: [],
    error: null,
  },
  ohlc: { D1: [], H4: [], H1: [] },
};

export const v2SuccessSummary: RunSummary = {
  symbol: "XAUUSD",
  date: "2026-07-26",
  time: "08",
  bias: "BULLISH",
  confidence: 72,
  action: "buy_setup",
  validation_status: "VALID",
  setup_status: "READY",
  direction: "LONG",
  operational: true,
  file_path: "2026/07/26/XAUUSD/result-08.json",
};

export const legacySummary: RunSummary = {
  symbol: "XAUUSD",
  date: "2026-07-25",
  time: "08",
  bias: "bullish",
  confidence: 0.85,
  action: "no_trade",
  validation_status: "UNKNOWN",
  setup_status: "UNKNOWN",
  direction: "NONE",
  operational: false,
  file_path: "2026/07/25/XAUUSD/result-08.json",
};
